It takes 15 minutes to create CloudSQL with db-f1-micro, and the default 5 minutes will cause a timeout.
Error: Could not connect to server: dial tcp 34.81.1.222:3306: connect: connection timed out