Fix error.
Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/google: locked provider registry.terraform.io/hashicorp/google
│ 4.16.0 does not match configured version constraint >= 3.38.0, >= 3.53.0,
│ ~> 4.37.0, < 5.0.0; must use terraform init -upgrade to allow selection of
│ new versions